version: '3.8'

services:
  master:
    build: .
    environment:
      SPRING_APPLICATION_JSON: '{
        "replication-log.is-replica":"false",
        "replication-log.replicas":"replica1:6565,replica2:6565"
      }'
    ports:
      - "8080:8080"
      - "6565:6565"

  replica1:
    build: .
    environment:
      SPRING_APPLICATION_JSON: '{
        "replication-log.is-replica":"true"
      }'
    ports:
       - "8081:8080"
       - "6566:6565"

  replica2:
    build: .
    environment:
      SPRING_APPLICATION_JSON: '{
        "replication-log.is-replica":"true",
        "replication-log.replication-delay":7000
      }'
    ports:
       - "8082:8080"
       - "6567:6565"
